### ISSUE TITLE
Suggested modifications: 2. Homeless decedents

### ISSUE THREAD

**Issue by mzakariaCERN** [mbg9700/IntroDSCapstone#3]
- [x] Convert the key variables you used to link WAMD with HDR to a list (just a markdown formatting issue)
-[ ] Mention the percentage of overlap that you got when using each key in that order. So the first attribute gave you, say, 80% identification, then adding the second attribute made it 90% etc.
- [x] Can you please mention that you did the same matching but this time in a reversed order and comment on the results (were they the same? did we miss few records? etc.)

**Comment by mbg9700** [comment]
Completed.  I got the same number of linked records when I did the steps in reverse.
